pipeline {
    agent any
    stages {
        stage ("git clone") {
            steps {
                git url: 'https://github.com/surendar9945/simple-java-maven-app.git'
            }    
        }

        stage ("Build") {
            steps {
                script {
                   sh  "mvn clean install"
                }
            }
        }

        stage ("CD") {
            steps {
                script {
                    sh ""
                    //sh "ansible-playbook -i {{inventory_name}} playbook"
                }
            }
        }
        
        stage ("notify") {
            steps {
                emailext body: 'this is status of job "${BUILD_URL}"', subject: 'Job Status', to: 'msurendar451@gmail.com'
            }
        }
    }
}
